project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data-analysis.qmd
        text: Data Analysis
      - href: source.qmd
        text: Source


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



